# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 299c91b771d47edc11d1c3485b5232c8b73315c60126eb75ddf8280d67c6e75e0b45b7ce51b1e48877d1150bb1978004b06c29a603fef5484a8667f53a335b9f

test:
  secret_key_base: 89d0303b5732a57b4253c72c35e477512c4f50858b766cbfefe1d1534940bf42a29fa8b3a5adac835281ee8202355d4c33f939402e9388871698a14cdc1cb514

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
